# import

In [17]:
%run ../src/ini.py

✅ Universal workspace ready!
save_in_data_folder_csv(df, file_name, sub_folder="")
load_data(relative_path_from_root="")
📍 Main folder: /Users/cristallagus/Desktop/IHK_Prüfung/IHK_Repo
📦 Modules loaded: FIS_broker_OSMnx_AfS_visualize_table_sorce, translatorV1, plotly_scater, geolocator_stread_around_sersch_4_3, geolocator_in_latitude_longitude, geolocator_stread_api_maching_standard, geolocator_produce_id, sql_database_conectors_image, sql_database_upload, sql_database_offline_download, sql_database_offline_in_df, install_MaiOmni, install_folder_index, pre_eda_words, pre_eda_data

In [16]:
#!pip install sqlalchemy langdetect pyperclip geoalchemy2

# data csv load

In [18]:
df = load_data("data/verbrauch.csv")

⚠️ HINWEIS: Automatische Erkennung hat Komma-Separator (sep=',') für 'data/verbrauch.csv' detektiert und angepasst.

In [19]:
full_data_analysis(df)

********** CONSOLIDATED DATA QUALITY ANALYSIS **********
                                                                                                                        -->  -->  -->
Shape (Rows, Columns): (16830, 16) | Duplicate Rows: 30
--------------------------------------------------
   Datentyp Semantischer_Typ  Einzigartige_Werte  Kardinalität(%)                            Spalte  Duplicate   NaN  NaN(%)      Min Lower_Fence 25% (Q1)   Median    StdDev  75% (Q3) Upper_Fence Max/100%(Q4) Skewness Ausreißer (IQR) Ausreißer (StdDev)
0    object               ID                 700             4.16                        zaehler_id      16130     0    0.00        -           -        -        -         -         -           -            -        -               -                  -
1    object               ID                 700             4.16                          kunde_id      16130     0    0.00        -           -        -        -         -         -           -            -        -               -                  -
2    object    Text (Gender)                  13             0.08                         kundentyp      16817     0    0.00        -           -        -        -         -         -           -            -        -               -                  -
3     int64            int64                 271             1.61               vertragsleistung_kw      16559     0    0.00     20.0      -156.5     49.0     82.0    147.51     186.0       391.5       1067.0     2.24            1204                337
4    object           object                  72             0.43                             monat      16758     0    0.00        -           -        -        -         -         -           -            -        -               -                  -
5     int64            int64                  12             0.07                         monat_idx      16818     0    0.00      1.0        -3.5      4.0      7.0      3.45       9.0        16.5         12.0     -0.0               0                  0
6     int64            int64                   4             0.02                       arbeitstage      16826     0    0.00     20.0        18.0     21.0     22.0      1.04      23.0        26.0         23.0    -0.24               0                  0
7     int64            int64                   3             0.02                feiertage_im_monat      16827     0    0.00      0.0        -1.5      0.0      0.5      0.64       1.0         2.5          2.0     0.64               0                  0
8   float64          float64                 269             1.60             mittlere_temperatur_c      16561   505    3.00     -4.6       -14.0      4.0     10.4      6.58      16.0        34.0         23.8    -0.04               0                  0
9     int64            int64                 204             1.21                          heiztage      16626     0    0.00      0.0      -428.0     22.0    162.0    151.23     322.0       772.0        540.0     0.23               0                  0
10  float64          float64                 701             4.17             produktionsplan_index      16129   673    4.00     0.58         0.6      0.9      1.0      0.13       1.1         1.4         1.41     0.01               5                  7
11    int64            int64                   2             0.01                     wartung_aktiv      16828     0    0.00      0.0         0.0      0.0      0.0      0.23       0.0         0.0          1.0     3.79             971                971
12  float64          float64               13308            79.07            vormonat_verbrauch_kwh       3522   700    4.16   147.82   -27283.25   7349.5  13592.0  29859.83   30438.0    65070.75    675230.57     3.48            1449                303
13  float64          float64               15844            94.14  letzte_3_monate_durchschnitt_kwh        986     1    0.01  1221.05    -27239.5   7605.0  14016.5  28264.97  30834.67    65679.17    353362.52     2.69            1446                322
14  float64          float64                7553            44.88       vorjahr_monat_verbrauch_kwh       9277  8412   49.98   229.78    -27520.0  7387.25  13651.0  30743.41  30658.75     65566.0    675230.57      4.0             753                143
15   object           object               13969            83.00                     verbrauch_kwh       2861     0    0.00        -           -        -        -         -         -           -            -        -               -                  -
                                                                                                                        -->  -->  -->
**************************************************
**********  DETECTING REDUNDANT COLUMNS BY CONTENT  **********
✅ No redundant columns detected.

In [20]:
full_words_analysis(df, target_col='kundentyp')

🚀 STARTING FULL COMPARISON ANALYSIS (5 Columns)
📊 1. STRUCTURE & QUALITY

               NaNs  Unique  Kardinalität % Dom. Sprache  Sonderzeichen
Spalte
zaehler_id        0     700             4.2          N/A          16830
kunde_id          0     700             4.2          N/A          16830
kundentyp         0      13             0.1          N/A              0
monat             0      72             0.4          N/A          11160
verbrauch_kwh     0   13969            83.0          N/A              2

🧠 2. CONTENT & SEMANTIC DEPTH

               Lex. Diversity  Stopword-Last                                                Top 5 Tokens  Zahlen im Text
Spalte
zaehler_id                1.0            0.0            zl-00011, zl-00015, zl-00041, zl-00070, zl-00100           16830
kunde_id                  1.0            0.0       kd-187498, kd-378167, kd-748143, kd-778843, kd-679879           16830
kundentyp                 1.0            0.0  gewerbe, industrie, kommunal, gewerbekunde, industriekunde               0
monat                     1.0            0.0                 08.2024, 07.2024, 11.2024, 01/2025, 03/2024           16830
verbrauch_kwh             1.0            0.0                         mwh, 6681.0, 5563.0, 7267.0, 8260.0           16830

📏 3. LENGTH STATISTICS (RAW DATA)

               Ø Zeichen  Max Zeichen  Ø Wörter  Max Wörter
Spalte
zaehler_id           8.0            8       1.0           1
kunde_id             9.0            9       1.0           1
kundentyp            7.8           14       1.0           1
monat                7.0            7       1.0           1
verbrauch_kwh        7.0           18       1.0           2

⚠️ 4. ANOMALY BOARD (MANCOS)

               Leere Texte  Short (<5)  Emojis  Shortforms  Shouting  Duplikate
Spalte
zaehler_id               0           0       0           0         0      16130
kunde_id                 0           0       0           0         0      16130
kundentyp                0           0       0           0         0      16817
monat                    0           0       0           0         0      16758
verbrauch_kwh            0           1       0           0         0       2861